### ISSUE TITLE
Dynamic URL

### ISSUE THREAD

**Issue by peterjkambey** [phpindonesia/phpindonesia.or.id-profile#2]
Banyak link-link (css, image, js) yang tidak bisa berfungsi selain http://localhost/phpindonesia/ padahal sudah disetting di po-config

sebisa mungkin dibuat dinamis agar tampilan tidak berantakan
![screen shot 2015-07-08 at 3 34 54 pm](https://cloud.githubusercontent.com/assets/1121775/8566239/06ed936c-2587-11e5-830f-20723e7ee7c8.png)

**Comment by DwiraSurvivor** [comment]
Tadi lupa nulis di README om, tapi sudah di tambahkan tadi caranya harus login ke po-adminboard kemudian ke menu setting/pengaturan terus sesuaikan url-nya di kotak WEB URL.
- Soalnya semua parameter url ngambil dari database "WEB URL" ini.
